micronaut:
  application:
    name: check-ins
  server:
    cors:
      enabled: true
    max-request-size: 100MB
    multipart:
      max-file-size: 100MB

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      default:
        enabled: true
        mapping: "/**"
        paths:
          - "classpath:public" 

  security:
    enabled: true
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: ${ OAUTH_CLIENT_ID }
          client-secret: ${ OAUTH_CLIENT_SECRET }
          openid:
            issuer: 'https://accounts.google.com'
    endpoints:
      logout:
        get-allowed: true
    intercept-url-map:
      -
        pattern: /**
        http-method: GET
        access:
          - isAuthenticated()
    reject-not-found: false
    redirect:
      login-success: /
      on-rejection: /oauth/login/google
      unauthorized:
        url: /oauth/login/google
      forbidden:
        url: /forbidden
    session:
      enabled: true
    netty:
      event-loops:
        io:
          num-threads: 4 #Matching number in database thread pool as that is currently our only use of I/O
---
datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql:///`}
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
    schema-generate: NONE
    maximum-pool-size: 4
---
check-ins:
  application:
    name: "OCI Check-ins"
    scopes:
      - "https://www.googleapis.com/auth/drive.file"
---
flyway:
  enabled: enabled
  datasources:
    default:
      locations: classpath:db
---
service-account-credentials:
  directory_id: ${ DIRECTORY_ID }
  type: ${ TYPE }
  project_id: ${ PROJECT_ID }
  private_key_id: ${ PRIVATE_KEY_ID }
  private_key: ${ PRIVATE_KEY }
  client_email: ${ CLIENT_EMAIL }
  client_id: ${ CLIENT_ID }
  auth_uri: ${ AUTH_URI }
  token_uri: ${ TOKEN_URI }
  auth_provider_x509_cert_url: ${ AUTH_PROVIDER_X509_CERT_URL }
  client_x509_cert_url: ${ CLIENT_X509_CERT_URL }
